version: '3'

services:
  sample:
    image: sample
    build:
      context: Dockerfiles
      dockerfile: Sample.Dockerfile

  lfi1:
    image: lfi1_fileread
    build:
      context: Dockerfiles
      dockerfile: LFI1.Dockerfile
    