# Generated by Django 3.2.12 on 2022-03-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('learn', '0003_auto_20220307_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='difficulty',
            field=models.CharField(
                choices=[(0, 'Difficulty Not Set'), (1, 'Very Easy'), (2, 'Easy'), (3, 'Normal'), (4, 'Hard'),
                         (5, 'Very Hard')], default=0, max_length=2),
        ),
    ]
