# Generated by Django 3.2.12 on 2022-03-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_lesson_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='order_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
