# Generated by Django 3.2.12 on 2022-03-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_alter_image_image_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_content',
            field=models.FileField(upload_to='apps/static/files/lessons'),
        ),
    ]
