# Generated by Django 3.2.12 on 2022-03-14 19:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0012_completedlessons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompletedLessons',
            new_name='CompletedLesson',
        ),
    ]
