# Generated by Django 4.0.4 on 2022-05-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('learn', '0014_alter_file_owner_alter_image_owner_alter_text_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
