# Generated by Django 3.2.12 on 2022-02-18 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('containers', '0003_alter_container_container_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=32)),
                ('image', models.CharField(max_length=32)),
                ('tag', models.CharField(default='latest', max_length=16)),
                ('exposed_ports', models.CharField(max_length=150)),
                ('duration', models.IntegerField(default=1800)),
                ('interactive_flag', models.BooleanField(default=False)),
                ('tty_flag', models.BooleanField(default=False)),
                ('rm_flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='container',
            name='container_name',
        ),
        migrations.RemoveField(
            model_name='container',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='container',
            name='exposed_ports',
        ),
        migrations.RemoveField(
            model_name='container',
            name='interactive_flag',
        ),
        migrations.RemoveField(
            model_name='container',
            name='rm_flag',
        ),
        migrations.RemoveField(
            model_name='container',
            name='tty_flag',
        ),
        migrations.AlterField(
            model_name='container',
            name='container_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='containers.image'),
        ),
    ]
