# Generated by Django 3.2.12 on 2022-02-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0005_auto_20220218_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='environment',
            field=models.CharField(default='{}', max_length=300),
        ),
        migrations.AlterField(
            model_name='image',
            name='exposed_ports',
            field=models.CharField(default='{}', max_length=150),
        ),
    ]
