# Generated by Django 3.2.12 on 2022-03-02 15:16

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('containers', '0007_container_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.utcnow),
        ),
    ]
