# Generated by Django 3.2.12 on 2022-03-13 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0011_alter_file_file_content'),
        ('containers', '0009_image_exploit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pre_lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='learn.lesson'),
        ),
    ]
