# Generated by Django 3.2.12 on 2022-03-14 12:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('containers', '0011_completedimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompletedImages',
            new_name='CompletedImage',
        ),
    ]
