# Generated by Django 3.2.12 on 2022-03-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0014_image_point_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='container_id',
            field=models.SlugField(blank=True, max_length=64, null=True),
        ),
    ]
