# Generated by Django 3.2.12 on 2022-04-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0015_alter_container_container_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='container_id',
            field=models.SlugField(default='0000000000000000', max_length=16),
        ),
    ]
