# Generated by Django 3.2.12 on 2022-04-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('containers', '0016_alter_container_container_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='container_id',
            field=models.SlugField(max_length=16, unique=True),
        ),
    ]
