# Generated by Django 3.2.12 on 2022-04-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('containers', '0017_alter_container_container_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='slug',
            field=models.SlugField(default='0000000000000000', max_length=16, unique=True),
        ),
    ]
