# Generated by Django 3.2.12 on 2022-04-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0019_auto_20220411_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='container_id',
            field=models.SlugField(default='0000000000000000', max_length=16, unique=True),
        ),
    ]
