# Generated by Django 4.0.4 on 2022-04-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0022_container_code_image_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='command',
            field=models.TextField(default='mvn test'),
        ),
    ]
