# Generated by Django 4.0.4 on 2022-04-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('containers', '0023_container_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='file_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
