# Generated by Django 4.0.4 on 2022-04-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('containers', '0024_container_file_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='command',
        ),
        migrations.RemoveField(
            model_name='container',
            name='file_location',
        ),
        migrations.AddField(
            model_name='image',
            name='command',
            field=models.TextField(default='mvn test'),
        ),
        migrations.AddField(
            model_name='image',
            name='file_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
