# Generated by Django 4.0.4 on 2022-04-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('containers', '0025_remove_container_command_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='detailed_description',
            field=models.TextField(default=''),
        ),
    ]
