# Generated by Django 4.0.4 on 2022-05-21 17:25

from django.db import migrations, models

import apps.containers.models


class Migration(migrations.Migration):
    dependencies = [
        ('containers', '0026_image_detailed_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='start_time',
            field=models.DateTimeField(blank=True, default=apps.containers.models.datetime_utc),
        ),
    ]
